<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <joint name="chassis_camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${cx/2-cam_l/2} 0 ${ch/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="0.0 0.0 ${cam_w/4}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${cam_l*0.75} ${cam_w*0.35} ${cam_w/2}"/>
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.0 0.0 ${cam_w*0.75}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${cam_l} ${cam_w/2} ${cam_w/2}"/>
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.0 ${-cam_w/4} ${cam_w*0.75}" rpy="0.0 ${pi/2} 0.0"/>
            <geometry>
                <cylinder radius="${cam_w/4}" length="${cam_l}"/>
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.0 ${cam_w/4} ${cam_w*0.75}" rpy="0.0 ${pi/2} 0.0"/>
            <geometry>
                <cylinder radius="${cam_w/4}" length="${cam_l}"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${cam_w/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${cam_l} ${cam_w} ${cam_w}"/>
            </geometry>
        </collision>
        <xacro:box_inertia x="${cam_l}" y="${cam_w}" z="${cam_w}">
            <origin xyz="0.0 0.0 ${cam_w/2}" rpy="0.0 0.0 0.0"/>
        </xacro:box_inertia>
    </link>

    <link name="iris_link">
        <visual>
            <geometry>
                <sphere radius="${cam_r}"/>
            </geometry>
            <material name="black" />
        </visual>
        <xacro:sphere_inertia r="${cam_r}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:sphere_inertia>
    </link>
    <joint name="iris_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="iris_link"/>
        <origin xyz="${cam_l/2} 0 ${cam_w*0.75}" rpy="0.0 ${radians(7.5)} 0.0"/>
    </joint>


     <joint name="camera_optical_joint" type="fixed">
        <parent link="iris_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>



    <gazebo reference="iris_link">
        <material>Gazebo/Black</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>30</update_rate>
            <camera>
                <horizontal_fov>${radians(40)}</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.001</near>
                    <far>3</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>